#!/usr/bin/env python3
"""
epub_to_markdown.py — Convert a complex EPUB into one self-contained markdown
file per logical section (chapter, essay, appendix...).

Tailored originally to HarperCollins' *The Study Quran* (Nasr et al., 2015),
which has:
  - 114 sura chapters, some split across .xhtml / Xa.xhtml / Xb.xhtml
  - Multiple frontmatter/backmatter essays
  - All footnote bodies collected in a single Footnote.xhtml file,
    with per-essay refs of the form `href="Footnote.xhtml#bX_fnN"`.

The script is generic enough that it can be reused on similar HarperCollins /
Calibre-derived EPUBs by editing the `plan.json` file alongside it.

Plan format:
{
  "epub": "path/to/book.epub",          # optional if --epub given
  "output_dir": "markdown",             # relative to plan dir, optional
  "footnote_file": "9780062227621_Footnote.xhtml",  # file that holds <p class="footnote"> bodies; refs point into it
  "sections": [
     {
       "title": "1 The Opening, al-Fātiḥah",
       "files": ["9780062227621_Chapter_1.xhtml"],
       "slug": "001_al-Fatihah"         # optional; autogenerated from title if omitted
     },
     {
       "title": "2 The Cow, al-Baqarah",
       "files": ["9780062227621_Chapter_2.xhtml",
                 "9780062227621_Chapter_2a.xhtml",
                 "9780062227621_Chapter_2b.xhtml"]
     },
     ...
  ]
}

Usage:
  python3 epub_to_markdown.py plan.json
  python3 epub_to_markdown.py plan.json --dry-run
  python3 epub_to_markdown.py plan.json --only "1 The Opening"
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import tempfile
import unicodedata
import zipfile
from pathlib import Path

from bs4 import BeautifulSoup
from bs4.element import NavigableString, Tag


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------

def _classes(node: Tag) -> list[str]:
    raw = node.get("class")
    if raw is None:
        return []
    if isinstance(raw, str):
        return raw.split()
    return [str(c) for c in raw]


def _attr(node: Tag, name: str) -> str:
    raw = node.get(name)
    if raw is None:
        return ""
    if isinstance(raw, str):
        return raw
    if isinstance(raw, (list, tuple)):
        return " ".join(str(x) for x in raw)
    return str(raw)


def slugify(text: str, maxlen: int = 90) -> str:
    """ASCII-safe, filesystem-friendly slug; keeps leading numeric prefix."""
    # Decompose accents then strip non-ASCII
    ascii_text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode()
    ascii_text = re.sub(r"[^\w\s-]", " ", ascii_text)
    ascii_text = re.sub(r"\s+", "_", ascii_text.strip())
    return ascii_text[:maxlen] or "section"


# ---------------------------------------------------------------------------
# XHTML → Markdown conversion
# ---------------------------------------------------------------------------

SKIP_CLASSES = {"image"}  # decorative images inline
SKIP_TAGS = {"style", "script", "meta", "link", "head", "title"}


class Converter:
    """Converts a soup body into markdown lines.

    Footnote bodies are loaded once from the shared Footnote file and resolved
    on demand when a `<sup><a href="...Footnote.xhtml#bX_fnN">` ref is encountered.
    Numbering within each output section is reset at convert_file() boundaries
    and assembled in read order.
    """

    def __init__(self, footnote_lookup: dict[str, str] | None = None,
                 footnote_file_marker: str | list[str] = "Footnote.xhtml",
                 section_title: str = ""):
        self.footnote_lookup = footnote_lookup or {}
        # Normalised section title, used to suppress an in-document heading that
        # merely repeats the plan-provided H1 (a very common EPUB duplication,
        # independent of the book's CSS classes).
        self.section_title_norm = re.sub(r"\s+", " ", section_title).strip().lower()
        self.used_footnotes: list[tuple[int, str]] = []
        self.footnote_counter = 0
        self.footnote_seen: dict[str, int] = {}
        # Substring(s) used to detect that a <sup><a href> points at the
        # footnote pool. Can be a single string or a list (any-match).
        # Examples:
        #   "Footnote.xhtml" — Study Quran
        #   "appendix001.html" — Davies *God and the New Physics*
        #   ["notas001.xhtml", "notas002.xhtml", ...] — Smith *El enigma
        #     cuántico* (one notes file per chapter)
        if isinstance(footnote_file_marker, str):
            raw_markers = [footnote_file_marker]
        else:
            raw_markers = list(footnote_file_marker)
        # Also match by basename: a plan may carry the pool as "text/Foo.xhtml"
        # while the in-document hrefs reference just "Foo.xhtml#anchor".
        markers: list[str] = []
        for m in raw_markers:
            if not m:
                continue
            if m not in markers:
                markers.append(m)
            base = m.rsplit("/", 1)[-1]
            if base and base not in markers:
                markers.append(base)
        self.footnote_markers: list[str] = markers

    # ---- footnote bookkeeping ----------------------------------------------

    def _resolve_footnote(self, anchor_id: str) -> int:
        """Return the 1-based local footnote number for a given `Footnote.xhtml#bX_fnN` anchor."""
        if anchor_id in self.footnote_seen:
            return self.footnote_seen[anchor_id]
        self.footnote_counter += 1
        num = self.footnote_counter
        self.footnote_seen[anchor_id] = num
        body = self.footnote_lookup.get(anchor_id, f"_[missing footnote: {anchor_id}]_")
        self.used_footnotes.append((num, body))
        return num

    # ---- inline -------------------------------------------------------------

    def _inline(self, node) -> str:
        if isinstance(node, NavigableString):
            return str(node)
        if not isinstance(node, Tag):
            return ""
        if node.name in SKIP_TAGS:
            return ""

        classes = _classes(node)
        # Drop decorative pagebreaks and images
        if _attr(node, "epub:type") == "pagebreak" or node.name == "img":
            return ""
        if "image" in classes:
            return ""
        # Special HarperCollins font spans just carry their content
        if set(classes) & {"HCSQ", "HCSQIt", "dropcap", "hide", "right_1"}:
            return "".join(self._inline(c) for c in node.children)
        # Verse number marker (`<span class="red1">42</span>`)
        if "red1" in classes:
            inner = "".join(self._inline(c) for c in node.children).strip()
            return f"**{inner}** " if inner else ""
        # Decorative red "verse start" glyph (fancy cap letter)
        if "redr" in classes:
            return "¶"
        if "red" in classes:
            return "".join(self._inline(c) for c in node.children)

        # Footnote reference: <sup><a href="...{marker}#anchor">N</a></sup>
        if node.name == "sup":
            a = node.find("a")
            if isinstance(a, Tag):
                href = _attr(a, "href")
                if any(m and m in href for m in self.footnote_markers):
                    anchor_id = href.split("#", 1)[1] if "#" in href else href
                    num = self._resolve_footnote(anchor_id)
                    return f"[^{num}]"
            # generic sup (e.g. mathematical exponents, "u", "un") → keep raw
            inner = "".join(self._inline(c) for c in node.children).strip()
            return f"^{inner}" if inner else ""

        if node.name == "i" or node.name == "em":
            inner = "".join(self._inline(c) for c in node.children)
            return f"*{inner}*" if inner.strip() else ""
        if node.name in ("b", "strong"):
            inner = "".join(self._inline(c) for c in node.children)
            return f"**{inner}**" if inner.strip() else ""
        if node.name == "br":
            return "\n"
        if node.name == "a":
            # Footnote reference where the <a> is the OUTER element wrapping a <sup>
            # (e.g. Davies's *God and the New Physics*:
            #   <a class="footnoteref" href=".../appendix001.html#ch2fn_1"><sup>1</sup></a>)
            # Also covers Smith's per-chapter notas files (multi-marker).
            href = _attr(node, "href")
            if any(m and m in href for m in self.footnote_markers):
                anchor_id = href.split("#", 1)[1] if "#" in href else href
                num = self._resolve_footnote(anchor_id)
                return f"[^{num}]"
            # Internal anchor: drop link, keep text
            return "".join(self._inline(c) for c in node.children)

        # Any other inline element — just descend
        return "".join(self._inline(c) for c in node.children)

    # ---- block --------------------------------------------------------------

    def _block(self, node) -> list[str]:
        if isinstance(node, NavigableString):
            text = str(node).strip()
            return [text] if text else []
        if not isinstance(node, Tag):
            return []
        if node.name in SKIP_TAGS:
            return []

        classes = _classes(node)

        # Skip decorative image wrappers
        if "image" in classes:
            return []

        name = node.name.lower()

        # Divs and sections: descend
        if name in ("section", "div", "body"):
            lines: list[str] = []
            if "quote" in classes:
                # Introductory quote/abstract → render as blockquote paragraph
                inner_blocks = []
                for child in node.children:
                    inner_blocks.extend(self._block(child))
                # prefix every non-empty line with "> "
                for block in inner_blocks:
                    if block.strip() == "":
                        lines.append("")
                    else:
                        for ln in block.splitlines():
                            lines.append(f"> {ln}" if ln.strip() else ">")
                    lines.append("")
                return lines
            for child in node.children:
                lines.extend(self._block(child))
            return lines

        # Headings
        if name in ("h1", "h2", "h3", "h4", "h5", "h6"):
            # Suppress title/subtitle headings that duplicate our plan-provided H1.
            # Study Quran uses h2/h2a/.../h2bm1; Davies's *God and the New Physics*
            # uses calibre7 and tocHead. Add classes here as new books surface.
            SKIP_HEADER_CLASSES = {"h2", "h2a", "h2b", "h2f", "h2bm", "h2bm1",
                                   "calibre7", "tocHead"}
            if set(classes) & SKIP_HEADER_CLASSES:
                return []
            text = self._inline(node).strip()
            text = re.sub(r"\s+", " ", text)
            if not text:
                return []
            # Suppress a heading that merely repeats the plan-provided section
            # title (generic de-duplication, no per-book class needed).
            if self.section_title_norm and text.lower() == self.section_title_norm:
                return []
            level_map = {"h1": 1, "h2": 2, "h3": 3, "h4": 4, "h5": 5, "h6": 6}
            hashes = "#" * level_map[name]
            return ["", f"{hashes} {text}", ""]

        if name == "p":
            # Star separators
            if "star" in classes or node.get_text().strip() in ("***", "* * *"):
                return ["", "---", ""]
            # Footnote paragraphs (in essays) → handled by caller via footnote file,
            # but if we encounter them inline here, emit as footnote body.
            if "footnote" in classes:
                return []
            if "h3l" in classes or "h3" in classes:
                # Verse quotations inside commentary → blockquote
                text = self._inline(node).strip()
                if not text:
                    return []
                return ["", f"> {text}", ""]
            text = self._inline(node)
            text = re.sub(r"[ \t]+", " ", text)
            text = text.strip()
            return ["", text, ""] if text else []

        if name == "h3":
            text = self._inline(node).strip()
            return ["", f"### {text}", ""] if text else []

        if name == "blockquote":
            inner = []
            for child in node.children:
                inner.extend(self._block(child))
            out = [""]
            for ln in "\n".join(inner).splitlines():
                out.append(f"> {ln}" if ln.strip() else ">")
            out.append("")
            return out

        if name == "ul":
            out = [""]
            for li in node.find_all("li", recursive=False):
                out.append(f"- {self._inline(li).strip()}")
            out.append("")
            return out

        if name == "ol":
            out = [""]
            for i, li in enumerate(node.find_all("li", recursive=False), 1):
                out.append(f"{i}. {self._inline(li).strip()}")
            out.append("")
            return out

        if name == "table":
            # Very light-weight table rendering
            rows = []
            for tr in node.find_all("tr"):
                cells = [self._inline(td).strip() for td in tr.find_all(["td", "th"])]
                rows.append("| " + " | ".join(cells) + " |")
            if rows:
                sep = "| " + " | ".join("---" for _ in rows[0].split("|")[1:-1]) + " |"
                rows.insert(1, sep)
                return ["", *rows, ""]
            return []

        # Fallback — descend
        lines = []
        for child in node.children:
            lines.extend(self._block(child))
        return lines

    # ---- public --------------------------------------------------------------

    def convert_file(self, html: str) -> list[str]:
        soup = BeautifulSoup(html, "html.parser")
        body = soup.body or soup
        lines = self._block(body)
        return lines


# ---------------------------------------------------------------------------
# Footnote loader
# ---------------------------------------------------------------------------

def load_footnote_lookup(html: str, fmt: str = "by_a_id") -> dict[str, str]:
    """Parse a footnote-pool file into {anchor_id -> markdown body}.

    Two formats are supported:

    * `by_a_id` (default, Study Quran / Davies pattern):
        <p class="footnote"><a id="bX_fnN" href="...">N.</a> body...</p>
      The id lives on the first <a> *inside* the paragraph.
    * `by_p_id` (Smith *El enigma cuántico* pattern):
        <div class="nota"><p id="ntN"><sup>[N]</sup> body... <a href="ref">&lt;&lt;</a></p></div>
      The id lives on the `<p>` itself; the body has a leading <sup>[N]</sup>
      and a trailing back-link `<a>` that we strip.
    """
    soup = BeautifulSoup(html, "html.parser")
    out: dict[str, str] = {}

    if fmt == "by_p_id":
        # Find all paragraphs with an id (they may be inside <div class="nota">).
        for p in soup.find_all("p"):
            if not isinstance(p, Tag):
                continue
            anchor_id = _attr(p, "id")
            if not anchor_id:
                continue
            # Drop the trailing back-link <a> (e.g. `<<`) if present.
            for a in list(p.find_all("a")):
                href = _attr(a, "href")
                if "#" in href and a.get_text(strip=True) in ("<<", "‹‹", "↩", "↑"):
                    a.extract()
            # Drop the leading <sup>[N]</sup>
            sup = p.find("sup")
            if isinstance(sup, Tag):
                inner = sup.get_text(strip=True)
                # Match patterns like "[1]" or "1"
                if re.fullmatch(r"\[?\d+\]?", inner):
                    sup.extract()
            conv = Converter(footnote_lookup={})
            text = "".join(conv._inline(c) for c in p.children)
            text = re.sub(r"^\s*\[?\d+\]?\.?\s*", "", text)
            text = re.sub(r"\s+", " ", text).strip()
            if text:
                out[anchor_id] = text
        return out

    # Default: by_a_id
    for p in soup.find_all("p", class_="footnote"):
        if not isinstance(p, Tag):
            continue
        a = p.find("a")
        if not isinstance(a, Tag):
            continue
        anchor_id = _attr(a, "id")
        if not anchor_id:
            continue
        a.extract()
        conv = Converter(footnote_lookup={})
        text = "".join(conv._inline(c) for c in p.children)
        text = re.sub(r"^\s*\d+\.\s*", "", text)
        text = re.sub(r"\s+", " ", text).strip()
        out[anchor_id] = text
    return out


# ---------------------------------------------------------------------------
# Post-processing
# ---------------------------------------------------------------------------

def tidy_markdown(lines: list[str]) -> str:
    """Collapse multiple blank lines, strip trailing whitespace, normalize."""
    out: list[str] = []
    prev_blank = False
    for ln in lines:
        rstripped = ln.rstrip()
        is_blank = rstripped == ""
        if is_blank and prev_blank:
            continue
        out.append(rstripped)
        prev_blank = is_blank
    # Strip leading/trailing blank lines
    while out and out[0].strip() == "":
        out.pop(0)
    while out and out[-1].strip() == "":
        out.pop()
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("plan", type=Path)
    ap.add_argument("--epub", type=Path, help="Override EPUB path from plan")
    ap.add_argument("--out", type=Path, help="Override output dir")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--only", type=str, help="Only process sections whose title contains this substring")
    args = ap.parse_args()

    plan = json.loads(args.plan.read_text(encoding="utf-8"))
    plan_dir = args.plan.parent.resolve()

    epub_path = args.epub or Path(plan["epub"])
    if not epub_path.is_absolute():
        epub_path = (plan_dir / epub_path).resolve()
    if not epub_path.is_file():
        sys.exit(f"EPUB not found: {epub_path}")

    output_dir = args.out or Path(plan.get("output_dir", "markdown"))
    if not output_dir.is_absolute():
        output_dir = (plan_dir / output_dir).resolve()

    # Extract to a temp dir
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        with zipfile.ZipFile(epub_path) as z:
            z.extractall(tmp_path)

        # Discover the text-content root. Strategy:
        #   1. Plan-level override (`text_dir`, relative to EPUB root) wins.
        #   2. Else look for a folder named text/Text (case-insensitive).
        #   3. Else fall back to the directory containing content.opf — this
        #      handles flat EPUBs (e.g. Wilber's Quantum Questions has all
        #      HTMLs directly in OEBPS/ alongside content.opf; Hacyan and
        #      Flew put HTMLs at the EPUB root).
        text_dir_override = plan.get("text_dir")
        if text_dir_override:
            text_root = (tmp_path / text_dir_override).resolve()
            if not text_root.is_dir():
                sys.exit(f"text_dir override not found: {text_root}")
        else:
            text_roots = [p for p in tmp_path.rglob("*")
                          if p.is_dir() and p.name.lower() == "text"]
            if text_roots:
                text_root = text_roots[0]
            else:
                opf_files = list(tmp_path.rglob("*.opf"))
                if not opf_files:
                    sys.exit(f"No text/ folder and no .opf in EPUB: {epub_path}")
                text_root = opf_files[0].parent
                print(f"info: no 'text/' folder; using OPF dir as text root: "
                      f"{text_root.relative_to(tmp_path)}", file=sys.stderr)

        # Load footnote lookup. `footnote_file` can be:
        #   - a string (single pool file, e.g. Footnote.xhtml or appendix001.html)
        #   - a list of strings (multiple pool files merged, e.g. Smith's
        #     notas001.xhtml … notas009.xhtml)
        # `footnote_format` controls how anchors are extracted (see
        # load_footnote_lookup): "by_a_id" (default) or "by_p_id".
        footnote_lookup: dict[str, str] = {}
        fn_file = plan.get("footnote_file")
        fn_files: list[str]
        if isinstance(fn_file, list):
            fn_files = [str(f) for f in fn_file]
        elif fn_file:
            fn_files = [str(fn_file)]
        else:
            fn_files = []
        fn_format = plan.get("footnote_format", "by_a_id")
        for fn in fn_files:
            fn_path = text_root / fn
            if fn_path.is_file():
                merged = load_footnote_lookup(fn_path.read_text(encoding="utf-8"),
                                              fmt=fn_format)
                # Detect collisions; warn if the same anchor lives in two pool files.
                for k, v in merged.items():
                    if k in footnote_lookup and footnote_lookup[k] != v:
                        print(f"warning: footnote anchor collision for "
                              f"{k!r} between pool files (later one wins)",
                              file=sys.stderr)
                    footnote_lookup[k] = v
            else:
                print(f"warning: footnote file not found: {fn_path}", file=sys.stderr)

        sections = plan.get("sections", [])
        output_dir.mkdir(parents=True, exist_ok=True)

        total = 0
        for i, sec in enumerate(sections):
            title = sec["title"]
            if args.only and args.only.lower() not in title.lower():
                continue

            slug = sec.get("slug") or f"{i:03d}_{slugify(title)}"
            out_path = output_dir / f"{slug}.md"

            # One converter per section so footnote numbering restarts.
            # The marker can be either a single string or a list (any-match).
            marker_for_conv: str | list[str]
            if not fn_files:
                marker_for_conv = "Footnote.xhtml"
            elif len(fn_files) == 1:
                marker_for_conv = fn_files[0]
            else:
                marker_for_conv = fn_files  # list — converter checks each
            conv = Converter(footnote_lookup=footnote_lookup,
                             footnote_file_marker=marker_for_conv,
                             section_title=title)
            parts: list[str] = [f"# {title}", ""]

            missing = []
            for f in sec["files"]:
                fp = text_root / f
                if not fp.is_file():
                    missing.append(f)
                    continue
                html = fp.read_text(encoding="utf-8")
                parts.extend(conv.convert_file(html))

            if missing:
                print(f"warning: missing files for '{title}': {missing}", file=sys.stderr)

            # Append footnote bodies
            if conv.used_footnotes:
                parts.extend(["", "---", "", "## Notes", ""])
                for num, body in conv.used_footnotes:
                    # Use markdown footnote syntax
                    body_oneline = re.sub(r"\s+", " ", body).strip()
                    parts.append(f"[^{num}]: {body_oneline}")

            content = tidy_markdown(parts)

            if args.dry_run:
                wc = len(content.split())
                print(f"  [{i:03d}] {title[:60]:<60}  -> {slug}.md  ({wc} words)")
                total += 1
                continue

            out_path.write_text(content, encoding="utf-8")
            wc = len(content.split())
            print(f"  [{i:03d}] wrote {slug}.md  ({wc} words)")
            total += 1

        print(f"\nDone. {total} section(s) {'planned' if args.dry_run else 'written'} in {output_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
