#!/usr/bin/env python3
"""
epub_to_markdown.py — Convert a complex EPUB into one self-contained markdown
file per logical section (chapter, essay, appendix...).

Tailored originally to HarperCollins' *The Study Quran* (Nasr et al., 2015),
which has:
  - 114 sura chapters, some split across .xhtml / Xa.xhtml / Xb.xhtml
  - Multiple frontmatter/backmatter essays
  - All footnote bodies collected in a single Footnote.xhtml file,
    with per-essay refs of the form `href="Footnote.xhtml#bX_fnN"`.

The script is generic enough that it can be reused on similar HarperCollins /
Calibre-derived EPUBs by editing the `plan.json` file alongside it.

Plan format:
{
  "epub": "path/to/book.epub",          # optional if --epub given
  "output_dir": "markdown",             # relative to plan dir, optional
  "footnote_file": "9780062227621_Footnote.xhtml",  # file that holds <p class="footnote"> bodies; refs point into it
  "sections": [
     {
       "title": "1 The Opening, al-Fātiḥah",
       "files": ["9780062227621_Chapter_1.xhtml"],
       "slug": "001_al-Fatihah"         # optional; autogenerated from title if omitted
     },
     {
       "title": "2 The Cow, al-Baqarah",
       "files": ["9780062227621_Chapter_2.xhtml",
                 "9780062227621_Chapter_2a.xhtml",
                 "9780062227621_Chapter_2b.xhtml"]
     },
     ...
  ]
}

Usage:
  python3 epub_to_markdown.py plan.json
  python3 epub_to_markdown.py plan.json --dry-run
  python3 epub_to_markdown.py plan.json --only "1 The Opening"
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import tempfile
import unicodedata
import zipfile
from pathlib import Path

from bs4 import BeautifulSoup
from bs4.element import NavigableString, Tag

from forja_common import slugify


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------

def _classes(node: Tag) -> list[str]:
    raw = node.get("class")
    if raw is None:
        return []
    if isinstance(raw, str):
        return raw.split()
    return [str(c) for c in raw]


def _attr(node: Tag, name: str) -> str:
    raw = node.get(name)
    if raw is None:
        return ""
    if isinstance(raw, str):
        return raw
    if isinstance(raw, (list, tuple)):
        return " ".join(str(x) for x in raw)
    return str(raw)


# ---------------------------------------------------------------------------
# XHTML → Markdown conversion
# ---------------------------------------------------------------------------

SKIP_CLASSES = {"image"}  # decorative images inline
SKIP_TAGS = {"style", "script", "meta", "link", "head", "title"}

# Local (same-file) footnote anchors: a ref `<a href="#footnote-015">1</a>` whose
# body lives in the same document as `<… id="footnote-015">…</…>`. This is the
# default Calibre / InDesign pattern (`_idFootnote`), distinct from the pooled
# `Footnote.xhtml#anchor` pattern handled via footnote_markers.
NOTE_ID_RE = re.compile(r"(footnote|endnote|fn|note|nota)[-_]?\d", re.IGNORECASE)
NOTE_CLASS_RE = re.compile(r"(footnote|endnote|nota|note)", re.IGNORECASE)


def styles_from_css(css: str) -> tuple[set[str], set[str]]:
    """Return ({classes that are italic}, {classes that are bold}) from a stylesheet.

    Calibre/Kindle EPUBs almost never use <i>/<em>: the emphasis lives in a
    class (`<span class="italic">`, or an opaque `<span class="calibre12">`
    whose rule is `font-style: italic`). Reading it from the book's OWN CSS
    keeps this general instead of hardcoding class names per book.
    """
    italic: set[str] = set()
    bold: set[str] = set()
    # Strip comments, then walk `selector { body }` rules.
    css = re.sub(r"/\*.*?\*/", " ", css, flags=re.S)
    for sel, body in re.findall(r"([^{}]+)\{([^{}]*)\}", css):
        is_it = re.search(r"font-style\s*:\s*(italic|oblique)", body, re.I)
        # `font-weight: bold` or a numeric weight of 600+.
        is_bd = (re.search(r"font-weight\s*:\s*bold", body, re.I)
                 or re.search(r"font-weight\s*:\s*([6-9]\d\d)", body))
        if not (is_it or is_bd):
            continue
        for part in sel.split(","):
            # Only take plain class selectors (`.italic`, `p.foo`): a compound
            # or descendant selector would over-apply.
            m = re.fullmatch(r"\s*[a-zA-Z0-9]*\.([A-Za-z0-9_-]+)\s*", part)
            if not m:
                continue
            if is_it:
                italic.add(m.group(1))
            if is_bd:
                bold.add(m.group(1))
    return italic, bold


class Converter:
    """Converts a soup body into markdown lines.

    Footnote bodies are loaded once from the shared Footnote file and resolved
    on demand when a `<sup><a href="...Footnote.xhtml#bX_fnN">` ref is encountered.
    Numbering within each output section is reset at convert_file() boundaries
    and assembled in read order.
    """

    def __init__(self, footnote_lookup: dict[str, str] | None = None,
                 footnote_file_marker: str | list[str] = "Footnote.xhtml",
                 section_title: str = "",
                 italic_classes: set[str] | None = None,
                 bold_classes: set[str] | None = None,
                 heading_paragraphs: dict[str, int] | None = None,
                 image_dir: str = "",
                 image_skip: set[str] | None = None):
        self.footnote_lookup = footnote_lookup or {}
        # Emphasis carried by CSS CLASS instead of <i>/<em> (Calibre and most
        # Kindle exports do this: <span class="italic"> or <span class="calibre12">
        # whose rule is `font-style: italic`). Derived from the book's own
        # stylesheets by styles_from_css(), so this is not a hardcoded guess.
        self.italic_classes = italic_classes or set()
        self.bold_classes = bold_classes or set()
        # {css_class: heading level} for books whose subheadings are bold <p>s
        # rather than <hN> (plan key `heading_paragraphs`).
        self.heading_paragraphs = heading_paragraphs or {}
        # Relative dir used in the markdown link, e.g. "imagenes". Empty = drop
        # images (previous behaviour). `image_skip` holds basenames to ignore
        # (the cover, decorative rules...).
        self.image_dir = image_dir
        self.image_skip = image_skip or set()
        self.used_images: set[str] = set()
        # Normalised section title, used to suppress an in-document heading that
        # merely repeats the plan-provided H1 (a very common EPUB duplication,
        # independent of the book's CSS classes).
        self.section_title_norm = re.sub(r"\s+", " ", section_title).strip().lower()
        # Local (same-file) footnote support: bare ids of note bodies found in
        # the file currently being converted, and that file's name (used to
        # namespace ids so two files in one section can't collide).
        self.local_note_ids: set[str] = set()
        self.current_file = ""
        self.used_footnotes: list[tuple[int, str]] = []
        self.footnote_counter = 0
        self.footnote_seen: dict[str, int] = {}
        # Substring(s) used to detect that a <sup><a href> points at the
        # footnote pool. Can be a single string or a list (any-match).
        # Examples:
        #   "Footnote.xhtml" — Study Quran
        #   "appendix001.html" — Davies *God and the New Physics*
        #   ["notas001.xhtml", "notas002.xhtml", ...] — Smith *El enigma
        #     cuántico* (one notes file per chapter)
        if isinstance(footnote_file_marker, str):
            raw_markers = [footnote_file_marker]
        else:
            raw_markers = list(footnote_file_marker)
        # Also match by basename: a plan may carry the pool as "text/Foo.xhtml"
        # while the in-document hrefs reference just "Foo.xhtml#anchor".
        markers: list[str] = []
        for m in raw_markers:
            if not m:
                continue
            if m not in markers:
                markers.append(m)
            base = m.rsplit("/", 1)[-1]
            if base and base not in markers:
                markers.append(base)
        self.footnote_markers: list[str] = markers

    # ---- footnote bookkeeping ----------------------------------------------

    def _resolve_footnote(self, anchor_id: str) -> int:
        """Return the 1-based local footnote number for a given `Footnote.xhtml#bX_fnN` anchor."""
        if anchor_id in self.footnote_seen:
            return self.footnote_seen[anchor_id]
        self.footnote_counter += 1
        num = self.footnote_counter
        self.footnote_seen[anchor_id] = num
        body = self.footnote_lookup.get(anchor_id, f"_[missing footnote: {anchor_id}]_")
        self.used_footnotes.append((num, body))
        return num

    # ---- inline -------------------------------------------------------------

    def _inline(self, node) -> str:
        if isinstance(node, NavigableString):
            # A newline in the SOURCE is just whitespace in HTML, but keeping it
            # verbatim breaks the line mid-sentence — and when it lands right
            # before a <sup> note ref, the call ends up alone on its own line,
            # which pandoc then renders as a separate paragraph. Collapse it to
            # a space; a real line break only comes from <br>, handled below.
            return re.sub(r"[ \t]*\n[ \t\r\n]*", " ", str(node))
        if not isinstance(node, Tag):
            return ""
        if node.name in SKIP_TAGS:
            return ""

        classes = _classes(node)
        # Drop decorative pagebreaks and images
        if _attr(node, "epub:type") == "pagebreak":
            return ""
        if node.name == "img":
            # Images are CONTENT in illustrated books (charts, talismans,
            # diagrams) and dropping them is a silent loss. With --images they
            # are copied out and linked; without it we keep the old behaviour.
            src = _attr(node, "src")
            if not self.image_dir or not src:
                return ""
            name = src.rsplit("/", 1)[-1]
            if name in self.image_skip:
                return ""
            self.used_images.add(src)
            alt = _attr(node, "alt").strip()
            return f"\n\n![{alt}]({self.image_dir}/{name})\n\n"
        if "image" in classes:
            return ""
        # Special HarperCollins font spans just carry their content
        if set(classes) & {"HCSQ", "HCSQIt", "dropcap", "hide", "right_1"}:
            return "".join(self._inline(c) for c in node.children)
        # Verse number marker (`<span class="red1">42</span>`)
        if "red1" in classes:
            inner = "".join(self._inline(c) for c in node.children).strip()
            return f"**{inner}** " if inner else ""
        # Decorative red "verse start" glyph (fancy cap letter)
        if "redr" in classes:
            return "¶"
        if "red" in classes:
            return "".join(self._inline(c) for c in node.children)

        # Footnote reference: <sup><a href="...{marker}#anchor">N</a></sup>
        if node.name == "sup":
            a = node.find("a")
            if isinstance(a, Tag):
                href = _attr(a, "href")
                if any(m and m in href for m in self.footnote_markers):
                    anchor_id = href.split("#", 1)[1] if "#" in href else href
                    num = self._resolve_footnote(anchor_id)
                    return f"[^{num}]"
            # generic sup (e.g. mathematical exponents, "u", "un") → keep raw
            inner = "".join(self._inline(c) for c in node.children).strip()
            return f"^{inner}" if inner else ""

        if node.name == "i" or node.name == "em":
            inner = "".join(self._inline(c) for c in node.children)
            return f"*{inner}*" if inner.strip() else ""
        if node.name in ("b", "strong"):
            inner = "".join(self._inline(c) for c in node.children)
            return f"**{inner}**" if inner.strip() else ""

        # Emphasis carried by CSS class (Calibre/Kindle). Keep the marks OUTSIDE
        # the surrounding whitespace: `*foo *bar` renders literally in pandoc.
        cls_italic = any(c in self.italic_classes for c in classes)
        cls_bold = any(c in self.bold_classes for c in classes)
        if (cls_italic or cls_bold) and node.name in ("span", "i", "em", "b",
                                                      "strong", "font"):
            inner = "".join(self._inline(c) for c in node.children)
            if not inner.strip():
                return inner
            lead = inner[:len(inner) - len(inner.lstrip())]
            trail = inner[len(inner.rstrip()):]
            core = inner.strip()
            if cls_bold:
                core = f"**{core}**"
            if cls_italic:
                core = f"*{core}*"
            return f"{lead}{core}{trail}"
        if node.name == "br":
            return "\n"
        if node.name == "a":
            # Footnote reference where the <a> is the OUTER element wrapping a <sup>
            # (e.g. Davies's *God and the New Physics*:
            #   <a class="footnoteref" href=".../appendix001.html#ch2fn_1"><sup>1</sup></a>)
            # Also covers Smith's per-chapter notas files (multi-marker).
            href = _attr(node, "href")
            if any(m and m in href for m in self.footnote_markers):
                anchor_id = href.split("#", 1)[1] if "#" in href else href
                num = self._resolve_footnote(anchor_id)
                return f"[^{num}]"
            # Local (same-file) footnote ref: href="#footnote-015" whose body was
            # indexed in this file by _index_local_footnotes().
            if href.startswith("#"):
                target = href[1:]
                if target in self.local_note_ids:
                    num = self._resolve_footnote(f"{self.current_file}::{target}")
                    return f"[^{num}]"
            # Internal anchor: drop link, keep text
            return "".join(self._inline(c) for c in node.children)

        # Any other inline element — just descend
        return "".join(self._inline(c) for c in node.children)

    # ---- block --------------------------------------------------------------

    def _block(self, node) -> list[str]:
        if isinstance(node, NavigableString):
            text = str(node).strip()
            return [text] if text else []
        if not isinstance(node, Tag):
            return []
        if node.name in SKIP_TAGS:
            return []

        classes = _classes(node)

        # Skip decorative image wrappers
        if "image" in classes:
            return []

        name = node.name.lower()

        # Divs and sections: descend
        if name in ("section", "div", "body"):
            lines: list[str] = []
            if "quote" in classes:
                # Introductory quote/abstract → render as blockquote paragraph
                inner_blocks = []
                for child in node.children:
                    inner_blocks.extend(self._block(child))
                # prefix every non-empty line with "> "
                for block in inner_blocks:
                    if block.strip() == "":
                        lines.append("")
                    else:
                        for ln in block.splitlines():
                            lines.append(f"> {ln}" if ln.strip() else ">")
                    lines.append("")
                return lines
            for child in node.children:
                lines.extend(self._block(child))
            return lines

        # Headings
        if name in ("h1", "h2", "h3", "h4", "h5", "h6"):
            # Suppress title/subtitle headings that duplicate our plan-provided H1.
            # Study Quran uses h2/h2a/.../h2bm1; Davies's *God and the New Physics*
            # uses calibre7 and tocHead. Add classes here as new books surface.
            SKIP_HEADER_CLASSES = {"h2", "h2a", "h2b", "h2f", "h2bm", "h2bm1",
                                   "calibre7", "tocHead"}
            if set(classes) & SKIP_HEADER_CLASSES:
                return []
            text = self._inline(node).strip()
            text = re.sub(r"\s+", " ", text)
            if not text:
                return []
            # Suppress a heading that merely repeats the plan-provided section
            # title (generic de-duplication, no per-book class needed).
            if self.section_title_norm and text.lower() == self.section_title_norm:
                return []
            level_map = {"h1": 1, "h2": 2, "h3": 3, "h4": 4, "h5": 5, "h6": 6}
            hashes = "#" * level_map[name]
            return ["", f"{hashes} {text}", ""]

        if name == "p":
            # Star separators
            if "star" in classes or node.get_text().strip() in ("***", "* * *"):
                return ["", "---", ""]
            # A paragraph whose WHOLE text is the section title is the book's own
            # chapter heading, styled as a bold <p> instead of an <h1> (the norm
            # in Calibre/Kindle exports). Suppress it: the plan already emits the
            # H1, and leaving it prints the title twice.
            if self.section_title_norm:
                ptext = re.sub(r"\s+", " ", node.get_text()).strip().lower()
                if ptext == self.section_title_norm:
                    return []
            # Book-specific subheadings styled as a bold <p> (plan key
            # `heading_paragraphs`: {css_class: level}). The class may sit on the
            # <p> or on a descendant <span>; Calibre nests them either way.
            if self.heading_paragraphs:
                seen = set(classes)
                for sp in node.find_all(("span", "div")):
                    seen.update(_classes(sp))
                for cls, level in self.heading_paragraphs.items():
                    if cls in seen:
                        text = re.sub(r"\s+", " ", self._inline(node)).strip()
                        # Drop the BOLD marks: a heading is already emphatic, and
                        # `## **X**` renders the asterisks in the TOC. A heading
                        # built from two adjacent bold spans ("Version I:" +
                        # "Part Three…") leaves `**` mid-string too, so remove
                        # them all — but keep single-`*` italics, which are
                        # meaningful in a title (work names, transliterations).
                        text = text.replace("**", "")
                        text = re.sub(r"\s+", " ", text).strip()
                        if not text:
                            return []
                        return ["", f"{'#' * level} {text}", ""]
            # Footnote paragraphs (in essays) → handled by caller via footnote file,
            # but if we encounter them inline here, emit as footnote body.
            if "footnote" in classes:
                return []
            if "h3l" in classes or "h3" in classes:
                # Verse quotations inside commentary → blockquote
                text = self._inline(node).strip()
                if not text:
                    return []
                return ["", f"> {text}", ""]
            text = self._inline(node)
            text = re.sub(r"[ \t]+", " ", text)
            text = text.strip()
            return ["", text, ""] if text else []

        if name == "h3":
            text = self._inline(node).strip()
            return ["", f"### {text}", ""] if text else []

        if name == "blockquote":
            inner = []
            for child in node.children:
                inner.extend(self._block(child))
            out = [""]
            for ln in "\n".join(inner).splitlines():
                out.append(f"> {ln}" if ln.strip() else ">")
            out.append("")
            return out

        if name == "ul":
            out = [""]
            for li in node.find_all("li", recursive=False):
                out.append(f"- {self._inline(li).strip()}")
            out.append("")
            return out

        if name == "ol":
            out = [""]
            for i, li in enumerate(node.find_all("li", recursive=False), 1):
                out.append(f"{i}. {self._inline(li).strip()}")
            out.append("")
            return out

        if name == "table":
            # Very light-weight table rendering
            rows = []
            for tr in node.find_all("tr"):
                cells = [self._inline(td).strip() for td in tr.find_all(["td", "th"])]
                rows.append("| " + " | ".join(cells) + " |")
            if rows:
                sep = "| " + " | ".join("---" for _ in rows[0].split("|")[1:-1]) + " |"
                rows.insert(1, sep)
                return ["", *rows, ""]
            return []

        # Fallback — descend
        lines = []
        for child in node.children:
            lines.extend(self._block(child))
        return lines

    # ---- public --------------------------------------------------------------

    def _local_note_body(self, el: Tag) -> str:
        """Extract a same-file footnote body, stripping its leading back-link
        and number marker."""
        target = el.find("p") or el
        if not isinstance(target, Tag):
            return ""
        # Drop return/back-link anchors (e.g. href="#footnote-015-backlink").
        for a in list(target.find_all("a")):
            if "backlink" in _attr(a, "href").lower():
                a.extract()
        text = "".join(self._inline(c) for c in target.children)
        text = re.sub(r"^\s*\[?\d+[.)\]]?\s*", "", text)   # leading "1 " / "1." / "[1]"
        return re.sub(r"\s+", " ", text).strip()

    def _index_local_footnotes(self, soup: BeautifulSoup) -> None:
        """Find note bodies referenced by same-file `href="#id"` anchors, fold
        their text into the footnote lookup, and remove them from the flow so
        they are not rendered inline."""
        targets = {
            _attr(a, "href")[1:]
            for a in soup.find_all("a")
            if _attr(a, "href").startswith("#")
        }
        for tid in targets:
            if not tid:
                continue
            el = soup.find(id=tid)
            if not isinstance(el, Tag):
                continue
            cls = " ".join(_classes(el))
            if not (NOTE_ID_RE.search(tid) or NOTE_CLASS_RE.search(cls)):
                continue  # ordinary cross-reference anchor, not a note
            key = f"{self.current_file}::{tid}"
            if key in self.footnote_lookup:
                continue
            body = self._local_note_body(el)
            if not body:
                continue
            self.footnote_lookup[key] = body
            self.local_note_ids.add(tid)
            el.decompose()

    def convert_file(self, html: str, filename: str = "") -> list[str]:
        soup = BeautifulSoup(html, "html.parser")
        self.current_file = filename
        self._index_local_footnotes(soup)
        body = soup.body or soup
        lines = self._block(body)
        return lines


# ---------------------------------------------------------------------------
# Footnote loader
# ---------------------------------------------------------------------------

def load_footnote_lookup(html: str, fmt: str = "by_a_id",
                         italic_classes: set[str] | None = None,
                         bold_classes: set[str] | None = None) -> dict[str, str]:
    """Parse a footnote-pool file into {anchor_id -> markdown body}.

    Three formats are supported:

    * `by_a_id` (default, Study Quran / Davies pattern):
        <p class="footnote"><a id="bX_fnN" href="...">N.</a> body...</p>
      The id lives on the first <a> *inside* the paragraph.
    * `by_p_id` (Smith *El enigma cuántico* pattern):
        <div class="nota"><p id="ntN"><sup>[N]</sup> body... <a href="ref">&lt;&lt;</a></p></div>
      The id lives on the `<p>` itself; the body has a leading <sup>[N]</sup>
      and a trailing back-link `<a>` that we strip.
    * `by_a_id_any` (Calibre/Kindle pattern, e.g. Picatrix Liber Atratus):
        <p class="calibre_2">[<a id="filepos…" href="…">N</a>] body...</p>
      Same idea as `by_a_id` but the paragraph carries an arbitrary class, so
      we accept ANY <p> whose first <a> has an id, and strip the surrounding
      brackets of the leading `[N]` marker.
    * `by_a_id_split` (Calibre/Kindle *flat* pool, e.g. Warnock & Greer's
      *Astral High Magic*):
        <p class="calibre_14">
          <a id="filepos…"></a>1. body… [<a href="…">return</a>]<br/><br/>
          <a id="filepos…"></a>2. body… [<a href="…">return</a>]<br/><br/>
        </p>
      ALL the notes live inside ONE paragraph, separated by <br/>, so there is
      no per-note element to iterate over: the note boundary is the empty
      `<a id=…></a>` anchor itself, and we split the raw HTML on it.
    """
    soup = BeautifulSoup(html, "html.parser")
    out: dict[str, str] = {}

    if fmt == "by_a_id_split":
        parts = re.split(r'<a\s+id="([^"]+)"\s*>\s*</a>', html)
        # parts = [preamble, id1, body1, id2, body2, …]
        for anchor_id, chunk in zip(parts[1::2], parts[2::2]):
            frag = BeautifulSoup(chunk, "html.parser")
            # Drop the trailing back-link ("[return]") and its brackets.
            for a in list(frag.find_all("a")):
                if a.get_text(strip=True).lower() in ("return", "back", "↩", "↑"):
                    a.decompose()
            conv = Converter(footnote_lookup={},
                             italic_classes=italic_classes,
                             bold_classes=bold_classes)
            text = "".join(conv._inline(c) for c in frag.children)
            text = re.sub(r"\[\s*\]\s*$", "", text.strip())
            # Leading note number left behind by the extracted anchor ("12. ").
            text = re.sub(r"^\s*\d+\.\s*", "", text)
            text = re.sub(r"\s+", " ", text).strip()
            if text:
                out[anchor_id] = text
        return out

    if fmt == "by_p_id":
        # Find all paragraphs with an id (they may be inside <div class="nota">).
        for p in soup.find_all("p"):
            if not isinstance(p, Tag):
                continue
            anchor_id = _attr(p, "id")
            if not anchor_id:
                continue
            # Drop the trailing back-link <a> (e.g. `<<`) if present.
            for a in list(p.find_all("a")):
                href = _attr(a, "href")
                if "#" in href and a.get_text(strip=True) in ("<<", "‹‹", "↩", "↑"):
                    a.extract()
            # Drop the leading <sup>[N]</sup>
            sup = p.find("sup")
            if isinstance(sup, Tag):
                inner = sup.get_text(strip=True)
                # Match patterns like "[1]" or "1"
                if re.fullmatch(r"\[?\d+\]?", inner):
                    sup.extract()
            conv = Converter(footnote_lookup={},
                             italic_classes=italic_classes,
                             bold_classes=bold_classes)
            text = "".join(conv._inline(c) for c in p.children)
            text = re.sub(r"^\s*\[?\d+\]?\.?\s*", "", text)
            text = re.sub(r"\s+", " ", text).strip()
            if text:
                out[anchor_id] = text
        return out

    # by_a_id (default) and by_a_id_any: the id lives on the first <a> inside
    # the paragraph. They differ only in which paragraphs are eligible.
    if fmt == "by_a_id_any":
        candidates = [p for p in soup.find_all("p") if isinstance(p, Tag)]
    else:
        candidates = [p for p in soup.find_all("p", class_="footnote")
                      if isinstance(p, Tag)]
    for p in candidates:
        a = p.find("a")
        if not isinstance(a, Tag):
            continue
        anchor_id = _attr(a, "id")
        if not anchor_id:
            continue
        a.extract()
        conv = Converter(footnote_lookup={},
                             italic_classes=italic_classes,
                             bold_classes=bold_classes)
        text = "".join(conv._inline(c) for c in p.children)
        # Leading marker left behind by the extracted <a>: "N." or the
        # brackets of "[N]" (by_a_id_any).
        text = re.sub(r"^\s*\d+\.\s*", "", text)
        text = re.sub(r"^\s*\[\s*\]\s*", "", text)
        text = re.sub(r"\s+", " ", text).strip()
        if text:
            out[anchor_id] = text
    return out


# ---------------------------------------------------------------------------
# Post-processing
# ---------------------------------------------------------------------------

def tidy_markdown(lines: list[str]) -> str:
    """Collapse multiple blank lines, strip trailing whitespace, normalize."""
    out: list[str] = []
    prev_blank = False
    for ln in lines:
        rstripped = ln.rstrip()
        is_blank = rstripped == ""
        if is_blank and prev_blank:
            continue
        out.append(rstripped)
        prev_blank = is_blank
    # Strip leading/trailing blank lines
    while out and out[0].strip() == "":
        out.pop(0)
    while out and out[-1].strip() == "":
        out.pop()
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("plan", type=Path)
    ap.add_argument("--epub", type=Path, help="Override EPUB path from plan")
    ap.add_argument("--out", type=Path, help="Override output dir")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--only", type=str, help="Only process sections whose title contains this substring")
    ap.add_argument("--images", type=str, default="",
                    help="Extract images into OUTPUT_DIR/NAME and link them "
                         "from the markdown (default: drop images)")
    ap.add_argument("--image-skip", type=str, default="",
                    help="Comma-separated image basenames to ignore (e.g. the cover)")
    args = ap.parse_args()

    plan = json.loads(args.plan.read_text(encoding="utf-8"))
    plan_dir = args.plan.parent.resolve()

    epub_path = args.epub or Path(plan["epub"])
    if not epub_path.is_absolute():
        epub_path = (plan_dir / epub_path).resolve()
    if not epub_path.is_file():
        sys.exit(f"EPUB not found: {epub_path}")

    output_dir = args.out or Path(plan.get("output_dir", "markdown"))
    if not output_dir.is_absolute():
        output_dir = (plan_dir / output_dir).resolve()

    # Extract to a temp dir
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        with zipfile.ZipFile(epub_path) as z:
            z.extractall(tmp_path)

        # Discover the text-content root. Strategy:
        #   1. Plan-level override (`text_dir`, relative to EPUB root) wins.
        #   2. Else look for a folder named text/Text (case-insensitive).
        #   3. Else fall back to the directory containing content.opf — this
        #      handles flat EPUBs (e.g. Wilber's Quantum Questions has all
        #      HTMLs directly in OEBPS/ alongside content.opf; Hacyan and
        #      Flew put HTMLs at the EPUB root).
        text_dir_override = plan.get("text_dir")
        if text_dir_override:
            text_root = (tmp_path / text_dir_override).resolve()
            if not text_root.is_dir():
                sys.exit(f"text_dir override not found: {text_root}")
        else:
            text_roots = [p for p in tmp_path.rglob("*")
                          if p.is_dir() and p.name.lower() == "text"]
            if text_roots:
                text_root = text_roots[0]
            else:
                opf_files = list(tmp_path.rglob("*.opf"))
                if not opf_files:
                    sys.exit(f"No text/ folder and no .opf in EPUB: {epub_path}")
                text_root = opf_files[0].parent
                print(f"info: no 'text/' folder; using OPF dir as text root: "
                      f"{text_root.relative_to(tmp_path)}", file=sys.stderr)

        # Emphasis-by-class map, read from the book's own stylesheets. Without
        # it, a Calibre/Kindle EPUB loses ALL its italics in silence (they are
        # <span class="italic">, never <i>), and in an academic text the italic
        # IS information: work titles, transliterations, technical terms.
        css_all = "\n".join(p.read_text(encoding="utf-8", errors="replace")
                            for p in sorted(tmp_path.rglob("*.css")))
        italic_classes, bold_classes = styles_from_css(css_all)
        if italic_classes or bold_classes:
            print(f"info: emphasis classes from CSS: "
                  f"{len(italic_classes)} italic, {len(bold_classes)} bold",
                  file=sys.stderr)

        heading_paragraphs = {str(k): int(v) for k, v in
                              (plan.get("heading_paragraphs") or {}).items()}
        image_dir = args.images or str(plan.get("image_dir") or "")
        image_skip = {s.strip() for s in
                      (args.image_skip or plan.get("image_skip") or "").split(",")
                      if s.strip()}
        all_used_images: set[str] = set()

        # Load footnote lookup. `footnote_file` can be:
        #   - a string (single pool file, e.g. Footnote.xhtml or appendix001.html)
        #   - a list of strings (multiple pool files merged, e.g. Smith's
        #     notas001.xhtml … notas009.xhtml)
        # `footnote_format` controls how anchors are extracted (see
        # load_footnote_lookup): "by_a_id" (default) or "by_p_id".
        footnote_lookup: dict[str, str] = {}
        fn_file = plan.get("footnote_file")
        fn_files: list[str]
        if isinstance(fn_file, list):
            fn_files = [str(f) for f in fn_file]
        elif fn_file:
            fn_files = [str(fn_file)]
        else:
            fn_files = []
        fn_format = plan.get("footnote_format", "by_a_id")
        for fn in fn_files:
            fn_path = text_root / fn
            if fn_path.is_file():
                merged = load_footnote_lookup(fn_path.read_text(encoding="utf-8"),
                                              fmt=fn_format,
                                              italic_classes=italic_classes,
                                              bold_classes=bold_classes)
                # Detect collisions; warn if the same anchor lives in two pool files.
                for k, v in merged.items():
                    if k in footnote_lookup and footnote_lookup[k] != v:
                        print(f"warning: footnote anchor collision for "
                              f"{k!r} between pool files (later one wins)",
                              file=sys.stderr)
                    footnote_lookup[k] = v
            else:
                print(f"warning: footnote file not found: {fn_path}", file=sys.stderr)

        sections = plan.get("sections", [])
        output_dir.mkdir(parents=True, exist_ok=True)

        total = 0
        for i, sec in enumerate(sections):
            title = sec["title"]
            if args.only and args.only.lower() not in title.lower():
                continue

            slug = sec.get("slug") or f"{i:03d}_{slugify(title, 90)}"
            out_path = output_dir / f"{slug}.md"

            # One converter per section so footnote numbering restarts.
            # The marker can be either a single string or a list (any-match).
            marker_for_conv: str | list[str]
            if not fn_files:
                marker_for_conv = "Footnote.xhtml"
            elif len(fn_files) == 1:
                marker_for_conv = fn_files[0]
            else:
                marker_for_conv = fn_files  # list — converter checks each
            conv = Converter(footnote_lookup=footnote_lookup,
                             footnote_file_marker=marker_for_conv,
                             section_title=title,
                             italic_classes=italic_classes,
                             bold_classes=bold_classes,
                             heading_paragraphs=heading_paragraphs,
                             image_dir=image_dir,
                             image_skip=image_skip)
            parts: list[str] = [f"# {title}", ""]

            missing = []
            for f in sec["files"]:
                fp = text_root / f
                if not fp.is_file():
                    missing.append(f)
                    continue
                html = fp.read_text(encoding="utf-8")
                parts.extend(conv.convert_file(html, filename=f))

            if missing:
                print(f"warning: missing files for '{title}': {missing}", file=sys.stderr)

            # Append footnote bodies
            if conv.used_footnotes:
                parts.extend(["", "---", "", "## Notes", ""])
                for num, body in conv.used_footnotes:
                    # Use markdown footnote syntax
                    body_oneline = re.sub(r"\s+", " ", body).strip()
                    parts.append(f"[^{num}]: {body_oneline}")

            content = tidy_markdown(parts)

            if args.dry_run:
                wc = len(content.split())
                print(f"  [{i:03d}] {title[:60]:<60}  -> {slug}.md  ({wc} words)")
                total += 1
                continue

            out_path.write_text(content, encoding="utf-8")
            all_used_images |= conv.used_images
            wc = len(content.split())
            print(f"  [{i:03d}] wrote {slug}.md  ({wc} words)")
            total += 1

        # Copy out only the images actually referenced by the written markdown.
        if image_dir and all_used_images and not args.dry_run:
            img_out = output_dir / image_dir
            img_out.mkdir(parents=True, exist_ok=True)
            copied = 0
            for src in sorted(all_used_images):
                cand = (text_root / src).resolve()
                if not cand.is_file():
                    hits = list(tmp_path.rglob(src.rsplit("/", 1)[-1]))
                    if not hits:
                        print(f"warning: image not found in EPUB: {src}", file=sys.stderr)
                        continue
                    cand = hits[0]
                (img_out / cand.name).write_bytes(cand.read_bytes())
                copied += 1
            print(f"info: copied {copied} image(s) into {img_out}", file=sys.stderr)

        print(f"\nDone. {total} section(s) {'planned' if args.dry_run else 'written'} in {output_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
